# Generated by Django 4.0 on 2021-12-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_registration_image_registration_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='pdf',
            new_name='leaving_certificate',
        ),
        migrations.AddField(
            model_name='registration',
            name='resultslip',
            field=models.FileField(null=True, upload_to='pages/pdfs/'),
        ),
    ]
