# Generated by Django 4.0 on 2021-12-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_pdf_registration_leaving_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='birth_cert',
            field=models.FileField(null=True, upload_to='pages/pdfs/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='id_card',
            field=models.FileField(null=True, upload_to='pages/pdfs/'),
        ),
    ]
