# Generated by Django 4.0 on 2021-12-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_registration_birth_cert_registration_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='medical_cert',
            field=models.FileField(null=True, upload_to='pages/pdfs/'),
        ),
    ]
